version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - database:/var/lib/mysql/
    networks:
      - app-network
	  
  # Node
  node:
    image: node:8.6-alpine
    container_name: node
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  database:
    driver: local